name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

repository: postgresapp/postgresapp

release: {
		name: {
			en: "Postgres.app with PostgreSQL 18 (Universal)",
			de: "Postgres.app mit PostgreSQL 18 (Universal)",
		},
		size: "122MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-18.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "18.2", postgis: "3.6.2", architecture: "Universal" },
		],
	}


extraReleases: [
	{
		name: {
			en: "Postgres.app with all currently supported versions (Universal)",
			de: "Postgres.app mit allen unterstützten Versionen (Universal)",
		},
		size: "532MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-14-15-16-17-18.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "18.2", postgis: "3.6.2", architecture: "Universal" },
			{ postgres: "17.8", postgis: "3.5.5", architecture: "Universal" },
			{ postgres: "16.12", postgis: "3.4.5", architecture: "Universal" },
			{ postgres: "15.16", postgis: "3.3.8", architecture: "Universal" },
			{ postgres: "14.21", postgis: "3.2.8", architecture: "Universal" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 17 (Universal)",
			de: "Postgres.app mit PostgreSQL 17 (Universal)",
		},
		size: "120MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-17.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "17.8", postgis: "3.5.5", architecture: "Universal" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 16 (Universal)",
			de: "Postgres.app mit PostgreSQL 16 (Universal)",
		},
		size: "113MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-16.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "16.12", postgis: "3.4.5", architecture: "Universal" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 15 (Universal)",
			de: "Postgres.app mit PostgreSQL 15 (Universal)",
		},
		size: "105MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-15.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "15.16", postgis: "3.3.8", architecture: "Universal" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 14 (Universal)",
			de: "Postgres.app mit PostreSQL 14 (Universal)",
		},
		size: "88MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.3/Postgres-2.9.3-14.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.3",
		postgresappVersion: "2.9.3",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "14.21", postgis: "3.2.8", architecture: "Universal" },
		],
	},
]

legacyReleases: [
	{
		name: {
			en: "Postgres.app with PostgreSQL 13 – 18 (Universal/Intel)",
			de: "Postgres.app mit PostgreSQL 13 – 18 (Universal/Intel)",
		},
		size: "584MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.9.2/Postgres-2.9.2-13-14-15-16-17-18.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.9.2",
		postgresappVersion: "2.9.2",
		postgresappMinSystemVersion: "10.15",
		postgresqlVersions: [
			{ postgres: "18.1", postgis: "3.6.1", architecture: "Universal" },
			{ postgres: "17.7", postgis: "3.5.4", architecture: "Universal" },
			{ postgres: "16.11", postgis: "3.4.4", architecture: "Universal" },
			{ postgres: "15.15", postgis: "3.3.8", architecture: "Universal" },
			{ postgres: "14.20", postgis: "3.2.8", architecture: "Universal" },
			{ postgres: "13.23", postgis: "3.1.12", plv8: "2.3.15", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 12 – 17 (Universal/Intel)",
			de: "Postgres.app mit PostgreSQL 12 – 17 (Universal/Intel)",
		},
		size: "510MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.7.10/Postgres-2.7.10-12-13-14-15-16-17.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.7.10",
		postgresappVersion: "2.7.10",
		postgresappMinSystemVersion: "10.13",
		postgresqlVersions: [
			{ postgres: "17.2", postgis: "3.5.0", architecture: "Universal" },
			{ postgres: "16.6", postgis: "3.4.3", architecture: "Universal" },
			{ postgres: "15.10", postgis: "3.3.7", architecture: "Universal" },
			{ postgres: "14.15", postgis: "3.2.7", architecture: "Universal" },
			{ postgres: "13.18", postgis: "3.1.11", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "12.22", postgis: "3.0.11", plv8: "2.3.15", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 11 – 16 (Universal/Intel)",
			de: "Postgres.app mit PostgreSQL 11 – 16 (Universal/Intel)",
		},
		size: "444MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.7/Postgres-2.7-11-12-13-14-15-16.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.7",
		postgresappVersion: "2.7",
		postgresappMinSystemVersion: "10.13",
		postgresqlVersions: [
			{ postgres: "16.1", postgis: "3.4.1", architecture: "Universal" },
			{ postgres: "15.5", postgis: "3.3.5", architecture: "Universal" },
			{ postgres: "14.10", postgis: "3.2.6", architecture: "Universal" },
			{ postgres: "13.13", postgis: "3.1.10", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "12.17", postgis: "3.0.10", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "11.22", postgis: "2.5.9", plv8: "2.3.15", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 10 – 15 (Universal/Intel)",
			de: "Postgres.app mit PostgreSQL 10 – 15 (Universal/Intel)",
		},
		size: "379MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.5.12/Postgres-2.5.12-10-11-12-13-14-15.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.5.12",
		postgresappVersion: "2.5.12",
		postgresappMinSystemVersion: "10.13",
		postgresqlVersions: [
			{ postgres: "15.1", postgis: "3.3.1", architecture: "Universal" },
			{ postgres: "14.6", postgis: "3.2.3", architecture: "Universal" },
			{ postgres: "13.9", postgis: "3.1.7", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "12.13", postgis: "3.0.7", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "11.18", postgis: "2.5.8", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "10.23", postgis: "2.4.10", plv8: "1.4.8", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Most recent version supported on macOS 10.12 (Universal/Intel)",
			de: "Letzte Version die macOS 10.12 unterstützt (Universal/Intel)",
		},
		size: "280MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.5.9/Postgres-2.5.9-10-11-12-13-14.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.5.9",
		postgresappVersion: "2.5.9",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "14.5", postgis: "3.2.2", architecture: "Universal" },
			{ postgres: "13.8", postgis: "3.1.6", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "12.12", postgis: "3.0.6", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "11.17", postgis: "2.5.7", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "10.22", postgis: "2.4.10", plv8: "1.4.8", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 9.6 – 14 (Universal/Intel)",
			de: "Postgres.app mit PostgreSQL 9.6 – 14 (Universal/Intel)",
		},
		size: "363MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.5.2/Postgres-2.5.2-9.6-10-11-12-13-14.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.5.2",
		postgresappVersion: "2.5.2",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "14.1", postgis: "3.1.4", architecture: "Universal" },
			{ postgres: "13.5", postgis: "3.1.4", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "12.9", postgis: "3.0.4", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "11.14", postgis: "2.5.5", plv8: "2.3.15", architecture: "Intel" },
			{ postgres: "10.19", postgis: "2.4.9", plv8: "1.4.8", architecture: "Intel" },
			{ postgres: "9.6.24", postgis: "2.3.11", plv8: "1.4.8", architecture: "Intel" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 9.5 – 13",
			de: "Postgres.app mit PostgreSQL 9.5 – 13",
		},
		size: "310MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.4.4/Postgres-2.4.4-9.5-9.6-10-11-12-13.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.4.4",
		postgresappVersion: "2.4.4",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "13.4", postgis: "3.1.3", plv8: "2.3.15" },
			{ postgres: "12.8", postgis: "3.0.3", plv8: "2.3.15" },
			{ postgres: "11.13", postgis: "2.5.5", plv8: "2.3.15" },
			{ postgres: "10.18", postgis: "2.4.9", plv8: "1.4.8" },
			{ postgres: "9.6.23", postgis: "2.3.11", plv8: "1.4.8" },
			{ postgres: "9.5.25", postgis: "2.2.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 9.4 - 12",
			de: "Postgres.app mit PostgreSQL 9.4 - 12",
		},
		size: "320MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.3.5/Postgres-2.3.5-9.4-9.5-9.6-10-11-12.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.3.5",
		postgresappVersion: "2.3.5",
		postgresappMinSystemVersion: "10.12",
		postgresqlVersions: [
			{ postgres: "12.3", postgis: "3.0.1", plv8: "2.3.14" },
			{ postgres: "11.8", postgis: "2.5.4", plv8: "2.3.14" },
			{ postgres: "10.13", postgis: "2.4.8", plv8: "1.4.8" },
			{ postgres: "9.6.18", postgis: "2.3.10", plv8: "1.4.8" },
			{ postgres: "9.5.22", postgis: "2.2.8", plv8: "1.4.8" },
			{ postgres: "9.4.26", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Postgres.app with PostgreSQL 9.5, 9.6 and 10",
			de: "Postgres.app mit PostgreSQL 9.5, 9.6 und 10",
		},
		size: "156MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-2.1.9.dmg",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappVersion: "2.1.9",
		postgresappMinSystemVersion: "10.10",
		postgresqlVersions: [
			{ postgres: "10.10", postgis: "2.4.7", plv8: "1.4.8" },
			{ postgres: "9.6.15", postgis: "2.3.9", plv8: "1.4.8" },
			{ postgres: "9.5.19", postgis: "2.2.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 10",
			de: "Legacy Postgres.app mit PostgreSQL 10",
		},
		size: "65MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-10.10.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "10.10", postgis: "2.4.7", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.6",
			de: "Legacy Postgres.app mit PostgreSQL 9.6",
		},
		size: "49MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.6.15.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.6.15", postgis: "2.3.9", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.5",
			de: "Legacy Postgres.app mit PostgreSQL 9.5",
		},
		size: "44MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.5.19.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.5.19", postgis: "2.2.8", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.4",
			de: "Legacy Postgres.app mit PostgreSQL 9.4",
		},
		size: "41MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-Legacy-9.4.24.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2.5",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.4.24", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
	{
		name: {
			en: "Legacy Postgres.app with PostgreSQL 9.3",
			de: "Legacy Postgres.app mit PostgreSQL 9.3",
		},
		size: "41MB",
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.4/Postgres-Legacy-9.3.23.zip",
		releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/tag/v2.1.4",
		postgresappMinSystemVersion: "10.7",
		postgresqlVersions: [
			{ postgres: "9.3.23", postgis: "2.1.9", plv8: "1.4.8" },
		],
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		homepage-button: Home,
		downloads-title: Downloads,
		download-button: Laden,
		docs-button: Doku,
		extensions-button: Erweiterungen,
		github-button: GitHub,
		stars: Sterne,
		find-us: Finde uns auf,
		typo: "Verbesserungsvorschläge für die Doku?",
		edit-page: Bearbeite diese Seite,
		requires-os: "Benötigt",
		download-size: "Downloadgröße",
		release-notes: "Versionshinweise",
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		homepage-button: Intro,
		downloads-title: Downloads,
		download-button: Download,
		docs-button: Docs,
		extensions-button: Extensions,
		github-button: GitHub,
		stars: Stars,
		find-us: Find us on,
		typo: "Do you have suggestions for improving the docs?",
		edit-page: edit this page,
		requires-os: "Requires",
		download-size: "Download Size",
		release-notes: "Release Notes",
	}
}
